CREATE TABLE CATEGORIES(
    ID SERIAL UNIQUE PRIMARY KEY NOT NULL,
    TYPE TEXT NOT NULL
);

CREATE TABLE ACCOUNT_TYPES(
    ID SERIAL UNIQUE PRIMARY KEY NOT NULL,
    TYPE TEXT NOT NULL
);

CREATE TABLE USERS(
    ID SERIAL UNIQUE PRIMARY KEY NOT NULL,
    DISPLAYNAME TEXT NOT NULL,
    PRIMARY_EMAIL TEXT,
    ALL_EMAIL TEXT[],
    PASSWORD TEXT,
    OLD_PASSWORDS TEXT[],
    ACCOUNT_ID INT REFERENCES ACCOUNT_TYPES (ID)
);

CREATE TABLE PROBLEMS(
    ID SERIAL UNIQUE PRIMARY KEY NOT NULL,
    DATE DATE,
    PROBLEM TEXT NOT NULL,
    CATEGORY_ID INT REFERENCES CATEGORY (ID),
    SOLUTION_ID INT REFERENCES SOLUTION_METHODS (ID),
    LEVEL INT NOT NULL,
    HINT TEXT,
    ANSWER TEXT,
    ANSWER_DESC TEXT
);

CREATE INDEX on PROBLEMS (DATE);

CREATE TABLE SOLUTION_METHODS(
    ID SERIAL UNIQUE PRIMARY KEY NOT NULL,
    TYPE TEXT NOT NULL
);


-- meh for now...
-- CREATE TABLE APPROVED_QUESTIONS(
--     USER_ID INT REFERENCES USERS (ID) NOT NULL,
--     PROBLEM_ID INT REFERENCES PROBLEMS (ID) NOT NULL,
--     APPROVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY(USER_ID, PROBLEM_ID)
-- );

-- CREATE TABLE CORRECT_ANSWERS(
--     USER_ID INT REFERENCES USERS (ID) NOT NULL,
--     PROBLEM_ID INT REFERENCES PROBLEMS (ID) NOT NULL,
--     ANSWERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY(USER_ID, PROBLEM_ID)
-- );